services:
  frontend:
    container_name: frontend
    restart: always
    # image: ghcr.io/slurfer/slurferpay:latest
    image: slurferpay:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
